### ISSUE TITLE
Rendering issues on android webkit browsers

### ISSUE THREAD

**Issue by Raynes** [Raynes/refheap#26]
Laying in bed looking at the site on my phone, there are a few small rendering issues.
- The main-right box is at a smaller width than in desktop browsers,  so the API portion is unreadable. Not even a scroll bar appears. 
- The paste links on the All Pastes that are on the right of the paste headers stick to the edge of the window if you zoom in away from them. Not sure if this is intentional. 

All in all, nothing major.

**Comment by amcnamara** [comment]
I guess overflow: auto defaults differently on mobile browsers.  We could force scroll but then FF looks like ass.

I'll hack on it once I get access to an android device, for now it's low priority since it's unlikely people will use mobile phones to enter code (it is very reasonable to assume they'll lookup previous pastes for their account or global-pastes though, can you verify that that experience is still smooth?).

**Comment by Raynes** [comment]
Yeah, it's mainly just that that is problematic. Definitely low-priority.

**Comment by amcnamara** [comment]
that box is also very broken on BB devices, for some reason the top li has a huge empty space... probably something to do with px-based padding on small resolution screens but I'm not sure

**Comment by Raynes** [comment]
These rendering issues no longer apply on android and I could care less about blackberry devices. Closing.
